name: Deploy to Firebase Hosting on Manual

on:
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4


      - name: Generate environment.prod.ts
        run: |
          mkdir -p src/environments
          echo "export const environment = {" > src/environments/environment.prod.ts
          echo "  production: true," >> src/environments/environment.prod.ts
          echo "  apiKey: '${{ secrets.APIKEY }}'," >> src/environments/environment.prod.ts
          echo "  authDomain: '${{ secrets.AUTHDOMAIN }}'," >> src/environments/environment.prod.ts
          echo "  projectId: '${{ secrets.PROJECTID }}'," >> src/environments/environment.prod.ts
          echo "  storageBucket: '${{ secrets.STORAGEBUCKET }}'," >> src/environments/environment.prod.ts
          echo "  messagingSenderId: '${{ secrets.MESSAGINGSENDERID }}'," >> src/environments/environment.prod.ts
          echo "  appId: '${{ secrets.APPID }}'," >> src/environments/environment.prod.ts
          echo "  measurementId: '${{ secrets.MEASUREMENTID }}'," >> src/environments/environment.prod.ts
          echo "  mpPublicKey: '${{ secrets.MPPUBLICKEY }}'," >> src/environments/environment.prod.ts
          echo "  urlBackendAPI: '${{ secrets.URLBACKENDAPI }}'" >> src/environments/environment.prod.ts
          echo "};" >> src/environments/environment.prod.ts

      - run: npm ci && npm run build

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_VIDEIRA_SA }}
          channelId: live
          projectId: videira-sa
